### ISSUE TITLE
MBP 13 mid 2012

### ISSUE THREAD

**Issue by pskowronek** [KrutavShah/MBP-Wireless-Upgrade#4]
Hi!

Very nice project, I'm glad that you made it open-source!
I have a question about MBP 13 mid 2012 - I see some files regarding MBP 15, will they be OK for 13"? If not, are you going to provide some designs for 13"?

Thanks in advance!

**Comment by KrutavShah** [comment]
My goal is to make one design that works for both models, but the problem I am seeing is that the screw holes and sizing is much more constrained. I don't own a 13 inch model so I would have to find someone that can provide measurements or borrow the laptop from someone.

**Comment by pskowronek** [comment]
I can help you with measurements I guess

**Comment by KrutavShah** [comment]
So I took a look and it appears that space is very much constrained in the 13 inch. The problem is that the wireless card assembly also holds the screw hole for the bottom shell of the MacBook. If I can find a solution for that, then this should be relatively straightforward.

Edit: the solution for this is to either cut it off from the assembly, purchase one pre-cut, or just not have it altogether and live with one less screw holding the back of the MacBook in. Let me know what you’re thinking.

**Comment by pskowronek** [comment]
Personally I think this single screw missing won't make any difference :) so anything that is easier to retrofit is better. Latter on, maybe somebody having this macbook and right tools will be able to prepare more advanced design.

(I assume you saw it, just in case: https://www.ifixit.com/Guide/MacBook+Pro+13-Inch+Unibody+Mid+2012+AirPort-Bluetooth+Board+Replacement/10363)

**Comment by KrutavShah** [comment]
That bracket does provide a level of structure for the right side of the MacBook and holds in the wires. 

At the end of the day, it's the person who is making this upgrade for their laptop that can choose whether they want the bracket or not, so if you dont want the bracket there, feel free to leave it out. The design for the actual upgrade will be the same regardless. 

With that out of the way, is there anything else we can discuss about the 13 inch MacBooks? My current focus is on the 15 inch.

**Comment by pskowronek** [comment]
So, basically, if wanted to upgrade MBP 13" is the procedure more or less the same as for 15"? The same card from newer macbooks and the board to properly connect antennas and wires?

**Comment by KrutavShah** [comment]
I believe only iMac wireless cards have the matching U.FL antenna connectors. This means that they will work right out of the box with the Unibody antennas. Only downside is that this card is the most expensive and largest one out of the other options. The MacBook Air and Pro wireless cards have the slightly smaller antenna connector, which you need to replace with the correct connectors by desoldering them off the old wireless card.

As for the card itself, we are trying to find the connector for the card but haven't had any luck yet, which means for now, you will have to actually solder the wireless card onto the adapter. If you have a soldering iron and hot air gun designed for soldering and electronics work, that shouldn't be too much of a problem. An example of this is the 862D+ which is one of the cheapest electronics rework stations.

Because this is being given out in the form of a file that you send to PCB manufacturer, you're going to have to build it yourself or find someone who is willing to, so it's not an out of the box solution.
