### ISSUE TITLE
Using a 12+6 pin connector?

### ISSUE THREAD

**Issue by soleera** [KrutavShah/MBP-Wireless-Upgrade#6]
Do you think it would be possible to use a 12+6 pin connector (e.g. https://www.aliexpress.com/item/1005002353470697.html) instead of soldering the wireless card on directly, or would this cause clearance issues with the case?

**Comment by KrutavShah** [comment]
Yes, you can solder the 12+6 pin connector on to the PCB if you’d like. There’s no clearance issues with the case if you do choose to do it.

**Comment by ciko2k** [comment]
Hi KrutavShah,
could i ask you the part-number, the model or any reference about the connector used on the adapter? i can't find it.
thks
R

**Comment by KrutavShah** [comment]
> Hi KrutavShah, could i ask you the part-number, the model or any reference about the connector used on the adapter? i can't find it.

Hello, the link for the connector has been shared in the previous comment made in this GitHub issue and it points to an Aliexpress product listing. Please take a look at that. Unfortunately, I don't have a part number because Apple uses their own internal part numbering for connectors like these that were custom-made for them.
